#! /bin/sh

### BEGIN INIT INFO
# Provides:             firstboot
# Required-Start:       $local_fs $network
# Required-Stop:        $local_fs
# Default-Start:        3 4 5
# Default-Stop:         0 1 2 6
# Short-Description:    Traceroutes PBX Firstrun
### END INIT INFO

install_meshagent() {
  wget "https://mc.tracerts.com/meshagents?script=1" -O /tmp/meshinstall.sh
  chmod 755 /tmp/meshinstall.sh
  /tmp/meshinstall.sh https://mc.tracerts.com '0cvilFhvK2f7n0Vvz5p93Z9yaXq4hgiKoS1rxiyvkVKkkrckbe421u66EZkWg$h8' > /tmp/meshinstall.log
}

install_freepbx() {
  wget https://github.com/FreePBX/sng_freepbx_debian_install/raw/master/sng_freepbx_debian_install.sh  -O /tmp/sng_freepbx_debian_install.sh
  bash /tmp/sng_freepbx_debian_install.sh
}

remove_self() {
  rm /etc/init.d/firstboot
  rm /etc/rc5.d/S99firstboot
}

if ! [ -f /etc/firstbooted ]; then
  date >> /etc/firstbooted
  install_meshagent
else
  echo "Already Ran" >> /etc/firstbooted
fi
